services:
  gridsome:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
        - ./:/usr/src/app
    command: "export NODE_OPTIONS=--openssl-legacy-provider && yarn run develop"